### ISSUE TITLE
example with emitters

### ISSUE THREAD

**Issue by jonathanong** [brentropy/chan#3]
i.e. if i want to do `fs.createWriteStream().on('finish', ch).on('error', ch)`

note: i'm opening up an issue instead of a PR because i expect there to be tests :P

**Comment by brentropy** [comment]
I will put this on the to-do list along with the tests.

**Comment by brentropy** [comment]
There is now a [stream example](https://github.com/brentburgoyne/chan/blob/master/examples/stream.js) that should cover using chan with an `EventEmitter`. Excerpt:

``` javascript
fs.createReadStream(__dirname + '/../README.markdown')
  .pipe(split())
  .on('data',  ch)
  .on('error', ch)
  .on('end',   ch.close);
```

Also, there are tests now.
