### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by juliangruber** [brentropy/chan#5]
something like this?

``` js
var ch = chan();

co(function*() {
  fs.readFile('file', ch);

  try {
    var contents = yield ch;
  } catch(err) {
    // handle the fs error
  }
});
```

**Comment by brentropy** [comment]
Yeah, that will work. There is [an example](https://github.com/brentburgoyne/chan/blob/master/examples/errors.js) for error handling now, but it doesn't look much different than what you have here.

**Comment by juliangruber** [comment]
nice!
